package com.company.Server.Enums;

public enum GoodsType {
    ELECTRONICS,
    HOUSEHOLD_TECHNIQUE,
    CLOTHES,
    SHOES,
    ACCESSORIES,
    BEAUTY,
    HEALTH,
    HOME_GOODS,
    CONSTRUCTION_AND_REPAIR,
    AUTO_GOODS,
    CHILD_GOODS,
    HOBBY_AND_CREATIVITY,
    SPORT_AND_RECREATION,
    FOODS,
    CHEMISTRY_GOODS,
    STATIONERY_SUPPLIES,
    ANIMALS_GOODS,
    BOOKS,
    FIELD_YARD_GARDEN_GARDEN
}
